---

- name: Deploying a rabbimq server
  hosts: rabbitmq
  become: yes
  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Upgrade all packages
      ansible.builtin.package:
        name: '*'
        state: latest

    - name: Install haproxy
      include_role:
        name: haproxy  
      when: ansible_hostname == 'server-rabbitmq-0'

    - name: Install rabbitmq
      include_role:
        name: rabbitmq

