---
- name: Add rabbitmq repo to repolist
  shell: "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"

- name: Import erlang repo key
  rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
    - https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.E495BB49CC4BBE5B.key

- name: Add erlang repo to yum.repos.d
  copy:
    src: erlang-latest.repo
    dest: /etc/yum.repos.d/ 

- name: Install dependencies
  package: 
    name: "{{ item }}"
  loop:
    - erlang
    - socat
    - logrotate
 
- name: Install rabbitmq-server
  package:
    name: rabbitmq-server
    state: latest

- name: Copy Rabitmq conf file
  copy:
    src: rabbitmq.conf
    dest: /etc/rabbitmq/rabbitmq.conf

- name: Enabling rabbitmq service
  shell: "chkconfig rabbitmq-server on"

- name: Start rabbitmq server
  service:
    name: rabbitmq-server
    state: started
